name: "CC By PR"
description: "validate PR for conventional commit"
branding:
  icon: "git-commit"
  color: "green"
inputs:
  pr-title-regex:
    description: "You can override the regex that is used to match PR title "
    required: false
    default: '^(revert: )?(feat|fix|docs|style|refactor|perf|test|chore|ci)(\(.+\))?: ([A-Z0-9].{1,49})'
  pr-body-regex:
    description: "You can override the regex that is used to match PR body "
    required: false
    default: '(.*\n)+(.*)'
runs:
  using: "node12"
  main: "./dist/index.js"
