name: PR
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, edited, synchronize]
jobs:
  cc-by-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cc-by-pr
        id: cc-by-pr
        uses: ns8482e/hello-action/actions/ccbypr@v5
