name: PR
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, edited, synchronize]
jobs:
  cc-by-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cc-by-pr
        id: cc-by-pr
        uses: ns8482e/hello-action/actions/ccbypr@v15
        with:
          success-msg:  The PR follows conventional commit
          fail-msg: The PR doesn't follow conventional commit 
          cc-by-pr-title: PR/cc-by-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
